[2024-07-10T13:26:40.853+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: spaceX_project.loading_into_db scheduled__2024-07-09T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
