[2024-07-09T08:21:20.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T08:21:20.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt.task2 scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T08:21:20.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt.task2 scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T08:21:20.669+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-09T08:21:20.685+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): task2> on 2024-07-08 00:00:00+00:00
[2024-07-09T08:21:20.692+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-09T08:21:20.694+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2024-07-09T08:21:20.694+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt', 'task2', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '514', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpqxifpys8']
[2024-07-09T08:21:20.695+0000] {standard_task_runner.py:91} INFO - Job 514: Subtask task2
[2024-07-09T08:21:20.743+0000] {task_command.py:426} INFO - Running <TaskInstance: elt.task2 scheduled__2024-07-08T00:00:00+00:00 [running]> on host f565c82ff71d
[2024-07-09T08:21:20.837+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dad' AIRFLOW_CTX_DAG_ID='elt' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-09T08:21:20.839+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T08:21:20.854+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO data
            VALUES
            (1,'Samir'),
            (2,'Aza'),
            (3,'Salya')
            ;        
        
[2024-07-09T08:21:20.863+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-09T08:21:20.872+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-09T08:21:20.876+0000] {sql.py:487} INFO - Running statement: 
            INSERT INTO data
            VALUES
            (1,'Samir'),
            (2,'Aza'),
            (3,'Salya')
            ;        
        , parameters: None
[2024-07-09T08:21:20.878+0000] {sql.py:496} INFO - Rows affected: 3
[2024-07-09T08:21:20.881+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T08:21:20.890+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt, task_id=task2, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240709T082120, end_date=20240709T082120
[2024-07-09T08:21:20.909+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-09T08:21:20.926+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T08:21:20.929+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-09T17:11:15.936+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T17:11:15.962+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt.task2 scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T17:11:15.974+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt.task2 scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T17:11:15.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-09T17:11:15.990+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): task2> on 2024-07-08 00:00:00+00:00
[2024-07-09T17:11:15.996+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-09T17:11:15.998+0000] {standard_task_runner.py:63} INFO - Started process 239 to run task
[2024-07-09T17:11:15.998+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt', 'task2', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '531', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpqwn9rmrd']
[2024-07-09T17:11:16.000+0000] {standard_task_runner.py:91} INFO - Job 531: Subtask task2
[2024-07-09T17:11:16.051+0000] {task_command.py:426} INFO - Running <TaskInstance: elt.task2 scheduled__2024-07-08T00:00:00+00:00 [running]> on host f565c82ff71d
[2024-07-09T17:11:16.143+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dad' AIRFLOW_CTX_DAG_ID='elt' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-09T17:11:16.144+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T17:11:16.158+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO data
            VALUES
            (1,'Samir'),
            (2,'Aza'),
            (3,'Salya')
            ;        
        
[2024-07-09T17:11:16.168+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-09T17:11:16.176+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-09T17:11:16.180+0000] {sql.py:487} INFO - Running statement: 
            INSERT INTO data
            VALUES
            (1,'Samir'),
            (2,'Aza'),
            (3,'Salya')
            ;        
        , parameters: None
[2024-07-09T17:11:16.185+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T17:11:16.187+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "data_pkey"
DETAIL:  Key (id)=(1) already exists.

[2024-07-09T17:11:16.202+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=elt, task_id=task2, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240709T171115, end_date=20240709T171116
[2024-07-09T17:11:16.219+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 531 for task task2 (duplicate key value violates unique constraint "data_pkey"
DETAIL:  Key (id)=(1) already exists.
; 239)
[2024-07-09T17:11:16.254+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T17:11:16.270+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T17:11:16.273+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
