[2024-07-11T13:16:24.887+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T13:16:24.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practise.inserting_into_table manual__2024-07-11T13:02:22.213405+00:00 [queued]>
[2024-07-11T13:16:24.929+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practise.inserting_into_table manual__2024-07-11T13:02:22.213405+00:00 [queued]>
[2024-07-11T13:16:24.930+0000] {taskinstance.py:2306} INFO - Starting attempt 11 of 16
[2024-07-11T13:16:24.946+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): inserting_into_table> on 2024-07-11 13:02:22.213405+00:00
[2024-07-11T13:16:24.952+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T13:16:24.953+0000] {standard_task_runner.py:63} INFO - Started process 254 to run task
[2024-07-11T13:16:24.953+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practise', 'inserting_into_table', 'manual__2024-07-11T13:02:22.213405+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpp4zktjbm']
[2024-07-11T13:16:24.955+0000] {standard_task_runner.py:91} INFO - Job 622: Subtask inserting_into_table
[2024-07-11T13:16:25.007+0000] {task_command.py:426} INFO - Running <TaskInstance: practise.inserting_into_table manual__2024-07-11T13:02:22.213405+00:00 [running]> on host b646c1147844
[2024-07-11T13:16:25.101+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='papik' AIRFLOW_CTX_DAG_ID='practise' AIRFLOW_CTX_TASK_ID='inserting_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T13:02:22.213405+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T13:02:22.213405+00:00'
[2024-07-11T13:16:25.102+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T13:16:25.116+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO tab(id,txt)
            VALUES
            (1,'df'),
            (2,'dss'),
            (3,'fds');
        
[2024-07-11T13:16:25.127+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-11T13:16:25.136+0000] {base.py:84} INFO - Using connection ID 'cosmos' for task execution.
[2024-07-11T13:16:25.141+0000] {sql.py:487} INFO - Running statement: 
            INSERT INTO tab(id,txt)
            VALUES
            (1,'df'),
            (2,'dss'),
            (3,'fds');
        , parameters: None
[2024-07-11T13:16:25.143+0000] {sql.py:496} INFO - Rows affected: 3
[2024-07-11T13:16:25.145+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T13:16:25.155+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practise, task_id=inserting_into_table, run_id=manual__2024-07-11T13:02:22.213405+00:00, execution_date=20240711T130222, start_date=20240711T131624, end_date=20240711T131625
[2024-07-11T13:16:25.209+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-11T13:16:25.226+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T13:16:25.229+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
